//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.MyStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPair
    {
        public int PatientID { get; set; }
        public int TestID { get; set; }
    }
}
